version: 2

project_name: delijn

changelog:
  disable: true

builds:
  - id: delijn
    main: ./cmd/delijn
    binary: delijn
    ldflags: >-
      -s -w
      -X github.com/dedene/delijn-cli/internal/cmd.version={{ .Tag }}
      -X github.com/dedene/delijn-cli/internal/cmd.commit={{ .ShortCommit }}
      -X github.com/dedene/delijn-cli/internal/cmd.date={{ .Date }}
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
  - id: delijn_darwin
    main: ./cmd/delijn
    binary: delijn
    ldflags: >-
      -s -w
      -X github.com/dedene/delijn-cli/internal/cmd.version={{ .Tag }}
      -X github.com/dedene/delijn-cli/internal/cmd.commit={{ .ShortCommit }}
      -X github.com/dedene/delijn-cli/internal/cmd.date={{ .Date }}
    env:
      - CGO_ENABLED=1
    targets:
      - darwin_amd64
      - darwin_arm64

archives:
  - builds:
      - delijn
      - delijn_darwin
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

brews:
  - repository:
      owner: dedene
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: Peter Dedene
      email: peter@dedene.com
    directory: Formula
    homepage: https://github.com/dedene/delijn-cli
    description: CLI for De Lijn - Flemish public transport departures, stops, and routes
    license: MIT
    install: |
      bin.install "delijn"
    test: |
      system "#{bin}/delijn", "--version"
