version: 2

project_name: delijn

changelog:
  disable: true

builds:
  - id: delijn
    main: ./cmd/delijn
    binary: delijn
    ldflags: >-
      -s -w
      -X github.com/dedene/delijn-cli/internal/cmd.version={{ .Tag }}
      -X github.com/dedene/delijn-cli/internal/cmd.commit={{ .ShortCommit }}
      -X github.com/dedene/delijn-cli/internal/cmd.date={{ .Date }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - ids:
      - delijn
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

brews:
  - repository:
      owner: dedene
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: Peter Dedene
      email: peter@dedene.com
    directory: Formula
    homepage: https://github.com/dedene/delijn-cli
    description: CLI for De Lijn - Flemish public transport departures, stops, and routes
    license: MIT
    install: |
      bin.install "delijn"
    test: |
      system "#{bin}/delijn", "--version"
